### ISSUE TITLE
Question about the project

### ISSUE THREAD

**Issue by Amy-Centrality** [akbaridria/gnf#1]
Hi there, Amy from Centrality here. Awesome work on this project! Very nice design and implementation!  

As a part of the judging criteria, we also need to verify the business model/plans. Could you please briefly explain, where you see TraPo in the future? and how is TraPo different and better than others? Do you have plans for attracting users or marketing?

**Comment by akbaridria** [comment]
Hi, amy. thankyou for reaching out me. honestly there are so many use case that exist in nft marketplace. but for my own point of view. in the first place. i want to make trapo as a developer pride. it means that you can buy nft in trapo and staked it. after buying this nft there are level for each nft. the higher your level the higher value of your nft. and you can increase your level by answering every technical question about web3. so its like "stackoverflow" but the more accepted answer you get. you get points from it and it can increase your nft level. deep down, i dont know if i can implement this idea into the real project.

**Comment by akbaridria** [comment]
> Hi there, Amy from Centrality here. Awesome work on this project! Very nice design and implementation!
> 
> As a part of the judging criteria, we also need to verify the business model/plans. Could you please briefly explain, where you see TraPo in the future? and how is TraPo different and better than others? Do you have plans for attracting users or marketing?

Hi, amy. thankyou for reaching out me. honestly there are so many use case that exist in nft marketplace. but for my own point of view. in the first place. i want to make trapo as a developer pride. it means that you can buy nft in trapo and staked it. after buying this nft there are level for each nft. the higher your level the higher value of your nft. and you can increase your level by answering every technical question about web3. so its like "stackoverflow" but the more accepted answer you get. you get points from it and it can increase your nft level. deep down, i dont know if i can implement this idea into the real project.

**Comment by Amy-Centrality** [comment]
I see. Thanks very much for the explanation! :) 
That's actually a really cool idea! For the DApp grant, we are after projects that can become self-sustaining projects. I think your submission has a good shot at winning the grant, if you could clearly reflect these ideas on the demo site or at least explain how it works in mockups or wireframes. Please show how you can earn the levels by answering questions, and how the levels affects the values of your NFT, can you buy a higher level by purchasing an NFT? :)

**Comment by Amy-Centrality** [comment]
Hi there, would you be keen to submite some changes to this project as suggested? We can wait for a couple more days if you were interested. As it stands, it's unlikely to take the winner prize due to idea not being original/specific enough.. It'd be really great if you could position the project to be what you mentioned above :)

**Comment by Amy-Centrality** [comment]
I was advised that the latest we can wait for would be tomorrow 12pm NZ time. We'll make a decision then :) best of luck! :)

**Comment by akbaridria** [comment]
> I was advised that the latest we can wait for would be tomorrow 12pm NZ time. We'll make a decision then :) best of luck! :)

hi amy, sorry for the late reply, first of all. it seems that i cant make it in time for the changes. and the second is rather than working alone in this project i think i want to create a solid team first before start the project again. about the prize in gitcoin bounty. i do realize that right now trapo will not be able to get the prize, and it is ok for me. atlease i learn a lot from this with nft module from cennznet. sorry if it is making you or team any trouble.

best regards,

Akbar Idria

**Comment by Amy-Centrality** [comment]
Thanks very much Akbar! We appreciate your awesome effort!
